-- MySQL Script generated by MySQL Workbench
-- Sun Oct 15 13:07:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Propietario` (
  `idPropietario` INT NOT NULL AUTO_INCREMENT,
  `Nombre_propietario` VARCHAR(45) NOT NULL,
  `Celular` VARCHAR(15) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPropietario`),
  UNIQUE INDEX `correo_UNIQUE` (`Correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Granja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Granja` (
  `idGranja` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Municipio` VARCHAR(45) NOT NULL,
  `Departamento` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `id_Propietario` INT NOT NULL,
  PRIMARY KEY (`idGranja`),
  INDEX `id_Propietario_idx` (`id_Propietario` ASC) VISIBLE,
  CONSTRAINT `id_Propietario`
    FOREIGN KEY (`id_Propietario`)
    REFERENCES `mydb`.`Propietario` (`idPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ganado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ganado` (
  `idGanado` INT NOT NULL AUTO_INCREMENT,
  `Num_registro` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `id_Granja` INT NOT NULL,
  PRIMARY KEY (`idGanado`),
  UNIQUE INDEX `Num_registro_UNIQUE` (`Num_registro` ASC) VISIBLE,
  INDEX `id_Granja_idx` (`id_Granja` ASC) VISIBLE,
  CONSTRAINT `id_Granja`
    FOREIGN KEY (`id_Granja`)
    REFERENCES `mydb`.`Granja` (`idGranja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Celular` VARCHAR(15) NOT NULL,
  `Marca_concentrado` VARCHAR(45) NOT NULL,
  `Cant_concentradoKg` FLOAT NOT NULL,
  `Precio_concentrado` INT NOT NULL,
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC) VISIBLE,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caracteristicas_Ganado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caracteristicas_Ganado` (
  `idCaracteristicas_Ganado` INT NOT NULL AUTO_INCREMENT,
  `Raza` VARCHAR(45) NOT NULL,
  `PesoKg` FLOAT NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Partos` INT NOT NULL,
  `Ordeño_mañanaLts` FLOAT NOT NULL,
  `Ordeño_tardeLts` FLOAT NOT NULL,
  `Concentrado` VARCHAR(45) NOT NULL,
  `Cant_concentradoKg` FLOAT NOT NULL,
  `Fecha_ordeño` DATE NOT NULL,
  `id_Ganado` INT NOT NULL,
  PRIMARY KEY (`idCaracteristicas_Ganado`),
  INDEX `id_Ganado_idx` (`id_Ganado` ASC) VISIBLE,
  CONSTRAINT `id_Ganado`
    FOREIGN KEY (`id_Ganado`)
    REFERENCES `mydb`.`Ganado` (`idGanado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Distrubucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Distrubucion` (
  `idDistrubucion` INT NOT NULL AUTO_INCREMENT,
  `id_Propietario` INT NOT NULL,
  `id_Proveedor` INT NOT NULL,
  PRIMARY KEY (`idDistrubucion`),
  INDEX `idProveedor_idx` (`id_Proveedor` ASC) VISIBLE,
  INDEX `idPropietario_idx` (`id_Propietario` ASC) VISIBLE,
  CONSTRAINT `idPropietario`
    FOREIGN KEY (`id_Propietario`)
    REFERENCES `mydb`.`Propietario` (`idPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProveedor`
    FOREIGN KEY (`id_Proveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
